name: Combine JSON Files

on:
  push:
    paths:
      - 'Shameless/**'
      - 'monstrum/**'
  schedule:
    - cron: '0 0 * * *'  # Optional: run daily at midnight

jobs:
  combine-json:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Run combine script
      run: python combine_json.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add combined_data.json
        git commit -m 'Automated combine JSON files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
