name: Combine JSON Files

on:
  push:
    paths:
      - 'Shameless/**'
      - 'Monstrum/**'
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  combine-json:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Run combine script
      run: python combine_json.py

    - name: Check for changes
      id: check_changes
      run: |
        if git diff --exit-code combined_data.json; then
          echo "No changes detected" > $GITHUB_ENV
        else
          echo "Changes detected" > $GITHUB_ENV
      continue-on-error: true

    - name: Commit and push changes
      if: env.CHANGES_DETECTED != 'No changes detected'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add combined_data.json
        git commit -m 'Automated combine JSON files'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
