name: Test Workflow

on:
  push:
    paths:
      - 'Shameless/**'
      - 'Monstrum/**'
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Display message
      run: echo "Workflow triggered!"
