name: Test Workflow

on:
  push:
    paths:
      - 'Shameless/**'
      - 'monstrum/**'

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Display message
      run: echo "Workflow triggered!"
